---
language: java
jdk: oraclejdk7
install:
- sudo apt-get install s3cmd
- sudo pip install mkdocs
before_script:
- export CROWDIN_PROJECT_ID="getlwc"
- export DOCS_BUCKET="docs.getlwc.org"
- '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && echo -e "[default]\naccess_key = $AWS_ACCESS_KEY_ID\nsecret_key=$AWS_SECRET_ACCESS_KEY"
  > .s3cfg'
- '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && sh backend/scripts/crowdin.sh'
script: mvn -Dmaven.javadoc.skip=true clean install
after_success:
- '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && mkdocs build --clean'
- '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && s3cmd sync --config .s3cfg --delete-removed
  site/. "s3://${DOCS_BUCKET}/"'
addons:
  artifacts:
    key:
      secure: et4n0n8tn9ghMJ0g/tYDN063NYNDotu0JM02hVDUMupGWkwZWKGPgPNWpDnW3To8Fmg5SRLIqphfAnR5t0dyY/Yp6xHXgSzheUA+4376cH6lirrQMRkmZ0nvK909thiy9uNAvPO3vBdP+kEWtLWLqvjv/z9VYMsc4ELrflLZHsc=
    secret:
      secure: c95q4+B3zAftsvUpTNE80/Q48YPxBVh+Mc5ZJ5wIBQ2SOyPygTca6I4AVBmrL0TQBfjBGmka49MCdvA11aglVT9vPfWxWIT9qSbJmuHXFY5RlUG6wtHlTw3wLnjrAw6zE0RDzG+E2sEDi81ADe43kG/9xMuzYdPjvEpFT5LK5hM=
    bucket: artifacts.getlwc.org
    paths:
    - $(git ls-files -x mcp -x original-*.jar -o *.jar *.zip | tr "\n" ":")
env:
  global:
  - secure: VWhdYVwHpkf688jTIvd87y6J62sIQDT3xzUHm9GGI8NPRVw37nv2SbnNqUO9728DrCCJoGSCmCiKCv483Kg6Zj4HmOZzDf+3nMsX6PtZjoIfetMH2QQ+X49bYtKXP3+gLhbt5tkKz0U5yaWA9aVllzn+5Fvrfpkpdel+etK8TXE=
  - secure: U1Plz/DgJroswv3pOoiAON4rEyhOxUHFcBay0bAfdFhcnZM4B1qgaKbIwij+qzpvTstkvFHfHsXF3gW7l64krA2s8UJnoO4uINIS7nC8OuMx2oiKCuIEhZ+YUnq+8U8cQbT9h81aNuL3czoRGWvA8fYiytrdUG9IhWhLBCUeqG4=
  - secure: pyXviFqSl/Nu+8L2CpMIT0b/fZ7ClsP7WWTlLWoiuII5sbd0vQitCpwBaa6HV78vsumE8PZmef+cprxO0uUd5DrYPADY71lCWyv8KWo1EBi/3tgztqtH6dzPizZy9b6lBhLmQrSQD+g7WCkjpKFLfdr/oWWkMzycxJikIXfU8g0=
